package packet.model;

public enum PacketType {
	ADV_IND, ADV_EXT_IND, AUX_ADV_IND, ADV_NONCONN_IND, CONNECT_IND, AUX_CONNECT_REQ, AUX_CONNECT_RSP, EMPTY_LL_DATA,
	LL_TERMINATE_IND, LL_DATA, LL_CONNECTION_PARAM_REQ, LL_CONNECTION_PARAM_RSP;
}
