package packet.model;

public enum Services {
	LINK_LOSS, CURRENT_TIME, GLUCOSE, DEVICE_INFORMATION, HEARTH_RATE, PHONE_ALERT_STATUS, BLOOD_PRESSURE,
	LOCATION_AND_NAVIGATION, EVNIRONMENTAL_SENSING, PULSE_OXYMETER, USER_DATA;
}
